# Generated by Django 6.0.2 on 2026-04-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('debut_date', models.DateField()),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('followers', models.IntegerField(default=0)),
                ('popularity_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Idol',
                'verbose_name_plural': 'Idols',
                'ordering': ['name'],
            },
        ),
    ]
