# Generated by Django 6.0.2 on 2026-04-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('straw_prod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='followers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
