# Generated by Django 6.0.2 on 2026-04-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('straw_prod', '0004_person_delete_actor_delete_idol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='talent_type',
            field=models.CharField(choices=[('idol', 'Idol'), ('actor', 'Actor')], default='idol', max_length=50),
        ),
    ]
